name: instagram_analytics
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^9.1.0
  provider: ^6.0.1
  cupertino_icons: ^1.0.2
  flutter_dialogs: ^2.1.1
  dots_indicator: ^2.0.0
  carousel_slider: ^4.0.0
  cached_network_image: ^3.1.0
  google_fonts: ^2.3.1
  shared_preferences: ^2.0.8
  flutter_overlay_loader: ^1.0.3
  sign_in_with_apple: ^3.2.0
  flutter_facebook_auth: ^4.1.1
  hive: ^2.0.5
  hive_flutter: ^1.0.0
  url_launcher: ^6.0.17
  modal_bottom_sheet: ^2.0.0
  intl: ^0.17.0
  charts_flutter: ^0.12.0
  image_cropper: ^1.5.0
  image_picker: ^0.8.4+10
  in_app_review: ^2.0.2
  permission_handler: ^8.3.0
  keyboard_actions: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
